name: myapp
description: A exported flutter project from FUNCTION12

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  firebase_core: any
  image_picker: ^1.0.4
  fluttertoast: ^8.2.2
  firebase_database: ^10.2.6
  confirm_dialog: ^1.0.2
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  page_transition: ^2.1.0
  flutter_local_notifications: ^9.8.0+1
  firebase_messaging: ^14.7.1
  intl: ^0.18.1
  rxdart: ^0.27.7
  pay: ^1.1.2
  url_launcher: ^6.2.1
  carousel_slider: ^4.2.1
  pie_chart: ^5.4.0
  fl_chart: ^0.64.0
  bottom_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/page-1/images/logomau.png"


flutter:


  uses-material-design: true

  assets:
    - lib/page-1/LienHe.dart
    - assets/
    - assets/page-1/
    - assets/page-1/images/
  fonts:
        - family: Quicksand
          fonts:
            - asset: assets/fonts/Quicksand-VariableFont_wght.ttf


