// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTO49_sM21B9bqvHFzpFjn2-an2NWQKiM',
    appId: '1:443225333655:web:c70ec74d426acbd68d6ed2',
    messagingSenderId: '443225333655',
    projectId: 'hicaphe',
    authDomain: 'hicaphe.firebaseapp.com',
    databaseURL: 'https://hicaphe-default-rtdb.firebaseio.com',
    storageBucket: 'hicaphe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqif278_LyXyIYN1-Zvqm6HtFTM9vGKPw',
    appId: '1:443225333655:android:5ca1bd7c6f8097448d6ed2',
    messagingSenderId: '443225333655',
    projectId: 'hicaphe',
    databaseURL: 'https://hicaphe-default-rtdb.firebaseio.com',
    storageBucket: 'hicaphe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmGJcq0KdkoYqHj61-8YLNlYXHQnvnjI',
    appId: '1:443225333655:ios:cca5f97f09d2784e8d6ed2',
    messagingSenderId: '443225333655',
    projectId: 'hicaphe',
    databaseURL: 'https://hicaphe-default-rtdb.firebaseio.com',
    storageBucket: 'hicaphe.appspot.com',
    iosBundleId: 'vn.com.hicaphe.hicaphe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmGJcq0KdkoYqHj61-8YLNlYXHQnvnjI',
    appId: '1:443225333655:ios:69e1316c1243ce868d6ed2',
    messagingSenderId: '443225333655',
    projectId: 'hicaphe',
    databaseURL: 'https://hicaphe-default-rtdb.firebaseio.com',
    storageBucket: 'hicaphe.appspot.com',
    iosBundleId: 'vn.com.hicaphe.hicaphe.RunnerTests',
  );
}
